// rn/src/features/direct-message/ui/MessageText.tsx
import { useMemo } from 'react';
import { Text, Linking, StyleSheet } from 'react-native';
import { splitMessageLinks } from '@/shared/lib/format-message-links';
import { useTheme } from '@/shared/theme/ThemeProvider';
import type { ThemeColors } from '@/shared/theme/colors';

interface MessageTextProps {
  text: string;
  isOwn?: boolean;
}

export function MessageText({ text, isOwn }: MessageTextProps) {
  const { colors } = useTheme();
  const styles = useMemo(() => createStyles(colors, isOwn), [colors, isOwn]);
  const segments = useMemo(() => splitMessageLinks(text), [text]);

  return (
    <Text style={styles.text}>
      {segments.map((segment, index) => {
        if (segment.type === 'link') {
          return (
            <Text
              key={`${index}-${segment.href}`}
              style={styles.link}
              onPress={() => void Linking.openURL(segment.href)}
            >
              {segment.value}
            </Text>
          );
        }
        return <Text key={`${index}-text`}>{segment.value}</Text>;
      })}
    </Text>
  );
}

function createStyles(colors: ThemeColors, isOwn?: boolean) {
  return StyleSheet.create({
    text: {
      fontSize: 15,
      lineHeight: 22,
      color: isOwn ? colors.primaryForeground : colors.foreground,
    },
    link: {
      textDecorationLine: 'underline',
    },
  });
}

// front/src/features/direct-message/ui/MessageText.vue
<script setup lang="ts">
import { computed } from 'vue'
import { splitMessageLinks } from '@/shared/lib/format-message-links'

const props = defineProps<{
  text: string
}>()

const segments = computed(() => splitMessageLinks(props.text))
</script>

<template>
  <span class="message-text">
    <template v-for="(segment, index) in segments" :key="index">
      <a
        v-if="segment.type === 'link'"
        :href="segment.href"
        class="message-text__link underline underline-offset-2 hover:opacity-80"
        target="_blank"
        rel="noopener noreferrer"
        @click.stop
      >
        {{ segment.value }}
      </a>
      <template v-else>{{ segment.value }}</template>
    </template>
  </span>
</template>
