// rn/src/entities/room/ui/LastRoomCard.tsx
import { useMemo } from 'react';
import { View, Text, Pressable, StyleSheet, Platform } from 'react-native';
import { ClockCounterClockwise } from 'phosphor-react-native';
import type { RoomType, VideoRoom } from '@/shared/api/room.types';
import { useTheme } from '@/shared/theme/ThemeProvider';
import type { ThemeColors } from '@/shared/theme/colors';

interface LastRoomCardProps {
  room: VideoRoom;
  roomType: RoomType;
  onPress: () => void;
}

function getAccent(colors: ThemeColors, roomType: RoomType) {
  if (roomType === 'youtube') return colors.youtube;
  if (roomType === 'soundcloud') return colors.soundcloud;
  return colors.belet;
}

function getSubtitle(room: VideoRoom, roomType: RoomType) {
  if (roomType === 'youtube' && room.youtubeVideoId) {
    return 'Continue where you left off';
  }
  if (roomType === 'soundcloud' && room.soundcloudTitle) {
    return room.soundcloudTitle;
  }
  if (roomType === 'belet' && room.beletTitle) {
    return room.beletTitle;
  }
  return `Room ${room.id.slice(0, 8)}`;
}

function getParticipantsLabel(count: number) {
  if (count === 0) return 'No one watching now';
  if (count === 1) return '1 watching';
  return `${count} watching`;
}

export function LastRoomCard({ room, roomType, onPress }: LastRoomCardProps) {
  const { colors } = useTheme();
  const accent = getAccent(colors, roomType);
  const styles = useMemo(() => createStyles(colors, accent), [colors, accent]);

  return (
    <Pressable
      onPress={onPress}
      style={({ pressed }) => [styles.card, pressed && styles.cardPressed]}
    >
      <View style={styles.iconWrap}>
        <ClockCounterClockwise size={16} color={accent} weight="bold" />
      </View>
      <View style={styles.body}>
        <Text style={styles.title}>Your last room</Text>
        <Text style={styles.subtitle} numberOfLines={1}>
          {getSubtitle(room, roomType)}
        </Text>
        <Text style={styles.meta}>{getParticipantsLabel(room.participants ?? 0)}</Text>
      </View>
    </Pressable>
  );
}

function createStyles(colors: ThemeColors, accent: string) {
  return StyleSheet.create({
    card: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      padding: 16,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: `${accent}4D`,
      backgroundColor: `${accent}0F`,
      ...(Platform.OS === 'web' ? { cursor: 'pointer' as const } : null),
    },
    cardPressed: {
      backgroundColor: `${accent}1A`,
    },
    iconWrap: {
      width: 40,
      height: 40,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: `${accent}40`,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.card,
    },
    body: {
      flex: 1,
      minWidth: 0,
    },
    title: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.foreground,
    },
    subtitle: {
      fontSize: 12,
      color: colors.muted,
      marginTop: 2,
    },
    meta: {
      fontSize: 11,
      color: `${colors.muted}CC`,
      marginTop: 4,
    },
  });
}

// front/src/entities/room/ui/LastRoomCard.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useRouter } from 'vue-router'
import { PhClockCounterClockwise } from '@phosphor-icons/vue'
import type { RoomType, VideoRoom } from '@/shared/api/room.types'

const props = defineProps<{
  room: VideoRoom
  roomType: RoomType
}>()

const router = useRouter()

const roomPath = computed(() =>
  props.roomType === 'youtube' ? `/room/${props.room.id}` : `/sound-room/${props.room.id}`,
)

const subtitle = computed(() => {
  if (props.roomType === 'youtube' && props.room.youtubeVideoId) {
    return 'Continue where you left off'
  }
  if (props.roomType === 'soundcloud' && props.room.soundcloudTitle) {
    return props.room.soundcloudTitle
  }
  return `Room ${props.room.id.slice(0, 8)}`
})

const participantsLabel = computed(() => {
  const count = props.room.participants
  if (count === 0) return 'No one watching now'
  if (count === 1) return '1 watching'
  return `${count} watching`
})

function openRoom() {
  router.push(roomPath.value)
}
</script>

<template>
  <button
    type="button"
    class="last-room-card surface flex w-full items-center gap-3 border-primary/30 bg-primary/5 p-4 text-left transition-colors hover:border-primary/50 hover:bg-primary/10"
    @click="openRoom"
  >
    <span
      class="last-room-card__icon flex size-9 shrink-0 items-center justify-center rounded-md bg-primary/10"
    >
      <PhClockCounterClockwise class="size-4 text-primary" />
    </span>

    <span class="last-room-card__body min-w-0 flex-1">
      <span class="last-room-card__title block text-sm font-medium">Your last room</span>
      <span class="last-room-card__subtitle mt-0.5 block truncate text-xs text-muted-foreground">
        {{ subtitle }}
      </span>
      <span class="last-room-card__meta mt-1 block text-[11px] text-muted-foreground/80">
        {{ participantsLabel }}
      </span>
    </span>
  </button>
</template>
