// front/src/features/room-share/ui/RoomShareCard.vue
<script setup lang="ts">
import { ref } from 'vue'
import { PhUserPlus } from '@phosphor-icons/vue'
import type { RoomType } from '@/shared/api/room.types'
import { Button } from '@/shared/ui/button'
import RoomInviteDialog from './RoomInviteDialog.vue'

defineProps<{
  url: string
  roomType: RoomType
}>()

const inviteOpen = ref(false)
</script>

<template>
  <section class="room-share-card rounded-xl border border-border/60 bg-card/40 p-4">
    <Button
      type="button"
      variant="secondary"
      class="room-share-card__invite w-full"
      @click="inviteOpen = true"
    >
      <PhUserPlus class="size-4" />
      Invite participant
    </Button>

    <RoomInviteDialog v-model:open="inviteOpen" :url="url" :room-type="roomType" />
  </section>
</template>

// rn/src/features/room-share/ui/RoomShareCard.tsx
import { useMemo, useState } from 'react';
import { View, StyleSheet } from 'react-native';
import { UserPlus } from 'phosphor-react-native';
import { Button } from '@/shared/ui/Button';
import { useTheme } from '@/shared/theme/ThemeProvider';
import type { ThemeColors } from '@/shared/theme/colors';
import type { RoomType } from '@/shared/api/room.types';
import { RoomInviteModal } from '@/features/room-share/ui/RoomInviteModal';

interface RoomShareCardProps {
  roomId: string;
  roomType: RoomType;
}

export function RoomShareCard({ roomId, roomType }: RoomShareCardProps) {
  const { colors } = useTheme();
  const styles = useMemo(() => createStyles(colors), [colors]);
  const [inviteOpen, setInviteOpen] = useState(false);

  return (
    <View style={styles.card}>
      <Button
        title="Invite participant"
        variant="outline"
        onPress={() => setInviteOpen(true)}
        icon={<UserPlus size={16} color={colors.foreground} />}
      />

      <RoomInviteModal
        visible={inviteOpen}
        roomId={roomId}
        roomType={roomType}
        onClose={() => setInviteOpen(false)}
      />
    </View>
  );
}

function createStyles(colors: ThemeColors) {
  return StyleSheet.create({
    card: {
      backgroundColor: colors.card,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 16,
    },
  });
}
