// front/src/features/room-player/ui/YoutubeVideoSearch.vue
<script setup lang="ts">
import { ref, watch } from 'vue'
import { Search } from 'lucide-vue-next'
import { Input } from '@/shared/ui/input'
import { youtubeAPI, type YoutubeVideo } from '@/shared/api/youtube.api'
import { extractYoutubeVideoId } from '../model/youtube.utils'

const emit = defineEmits<{
  select: [video: YoutubeVideo]
}>()

const searchQuery = ref('')
const suggestions = ref<YoutubeVideo[]>([])
const isSearching = ref(false)
const searchError = ref<string | null>(null)

async function searchVideos(query: string) {
  if (!query.trim()) {
    suggestions.value = []
    return
  }

  const videoId = extractYoutubeVideoId(query)
  if (videoId) {
    suggestions.value = [{ videoId, title: 'YouTube video' }]
    return
  }

  try {
    isSearching.value = true
    searchError.value = null
    suggestions.value = await youtubeAPI.searchVideos(query, 10)
  } catch (err: unknown) {
    searchError.value = err instanceof Error ? err.message : 'Failed to search'
    suggestions.value = []
  } finally {
    isSearching.value = false
  }
}

let searchDebounce: number | undefined
watch(searchQuery, (value) => {
  if (searchDebounce) clearTimeout(searchDebounce)

  if (!value.trim()) {
    suggestions.value = []
    searchError.value = null
    return
  }

  searchDebounce = window.setTimeout(() => {
    searchVideos(value)
  }, 400)
})

function selectVideo(video: YoutubeVideo) {
  suggestions.value = []
  searchQuery.value = ''
  searchError.value = null
  emit('select', video)
}

function submitSearch() {
  const videoId = extractYoutubeVideoId(searchQuery.value)
  if (videoId) {
    selectVideo({ videoId, title: 'YouTube video' })
    return
  }

  if (suggestions.value.length === 1) {
    selectVideo(suggestions.value[0]!)
  }
}
</script>

<template>
  <div class="youtube-video-search relative">
    <div class="youtube-video-search__field relative">
      <Search
        class="youtube-video-search__icon pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"
      />
      <Input
        v-model="searchQuery"
        class="youtube-video-search__input h-10 border-border/60 bg-background/60 pl-9 shadow-none"
        type="text"
        placeholder="Search or paste YouTube link"
        @keyup.enter="submitSearch"
      />
    </div>

    <p v-if="searchError" class="youtube-video-search__error mt-2 text-xs text-destructive">
      {{ searchError }}
    </p>

    <p
      v-else-if="isSearching"
      class="youtube-video-search__status mt-2 text-xs text-muted-foreground"
    >
      Searching...
    </p>

    <ul
      v-if="suggestions.length"
      class="youtube-video-search__suggestions absolute z-10 mt-2 max-h-64 w-full overflow-y-auto rounded-xl border border-border/60 bg-card/95 p-1 shadow-lg backdrop-blur-sm"
    >
      <li
        v-for="video in suggestions"
        :key="video.videoId"
        class="youtube-video-search__item flex cursor-pointer items-center gap-3 rounded-lg px-2 py-2 transition-colors hover:bg-muted/50"
        @click="selectVideo(video)"
      >
        <img
          v-if="video.thumbnailUrl"
          :src="video.thumbnailUrl"
          alt=""
          class="youtube-video-search__thumbnail size-10 shrink-0 rounded-md object-cover"
        />
        <div class="youtube-video-search__meta min-w-0 flex-1">
          <p class="youtube-video-search__title truncate text-sm font-medium">
            {{ video.title }}
          </p>
          <p
            v-if="video.channelTitle"
            class="youtube-video-search__channel truncate text-xs text-muted-foreground"
          >
            {{ video.channelTitle }}
          </p>
        </div>
      </li>
    </ul>
  </div>
</template>

// rn/src/features/room-player/ui/YoutubeVideoSearch.tsx
import { useEffect, useMemo, useState } from 'react';
import {
  View,
  Text,
  ScrollView,
  Pressable,
  Image,
  StyleSheet,
  Alert,
} from 'react-native';
import { MagnifyingGlass } from 'phosphor-react-native';
import { youtubeAPI, type YoutubeVideo } from '@/shared/api/youtube.api';
import { extractYoutubeVideoId } from '@/shared/lib/youtube-url';
import { Input } from '@/shared/ui/Input';
import { useTheme } from '@/shared/theme/ThemeProvider';
import type { ThemeColors } from '@/shared/theme/colors';

interface YoutubeVideoSearchProps {
  onSelect: (video: YoutubeVideo) => void;
}

export function YoutubeVideoSearch({ onSelect }: YoutubeVideoSearchProps) {
  const { colors } = useTheme();
  const styles = useMemo(() => createStyles(colors), [colors]);

  const [query, setQuery] = useState('');
  const [results, setResults] = useState<YoutubeVideo[]>([]);
  const [isSearching, setIsSearching] = useState(false);
  const [searchError, setSearchError] = useState<string | null>(null);

  useEffect(() => {
    if (!query.trim()) {
      setResults([]);
      setSearchError(null);
      return;
    }

    const timer = setTimeout(async () => {
      const videoId = extractYoutubeVideoId(query);
      if (videoId) {
        setResults([{ videoId, title: 'YouTube video' }]);
        setSearchError(null);
        setIsSearching(false);
        return;
      }

      setIsSearching(true);
      setSearchError(null);
      try {
        setResults(await youtubeAPI.searchVideos(query.trim(), 10));
      } catch (err: unknown) {
        const message = err instanceof Error ? err.message : 'Search failed';
        setSearchError(message);
        setResults([]);
        Alert.alert('Error', message);
      } finally {
        setIsSearching(false);
      }
    }, 400);

    return () => clearTimeout(timer);
  }, [query]);

  function selectVideo(video: YoutubeVideo) {
    setQuery('');
    setResults([]);
    setSearchError(null);
    onSelect(video);
  }

  function submitSearch() {
    const videoId = extractYoutubeVideoId(query);
    if (videoId) {
      selectVideo({ videoId, title: 'YouTube video' });
      return;
    }
    if (results.length === 1) {
      selectVideo(results[0]!);
    }
  }

  return (
    <View style={styles.root}>
      <View style={styles.field}>
        <View style={styles.searchIcon} pointerEvents="none">
          <MagnifyingGlass size={18} color={colors.muted} weight="bold" />
        </View>
        <Input
          value={query}
          onChangeText={setQuery}
          placeholder="Search or paste YouTube link"
          autoCapitalize="none"
          autoCorrect={false}
          returnKeyType="search"
          onSubmitEditing={submitSearch}
          style={styles.input}
        />
      </View>

      {searchError ? <Text style={styles.error}>{searchError}</Text> : null}
      {!searchError && isSearching ? (
        <Text style={styles.status}>Searching...</Text>
      ) : null}

      {results.length > 0 ? (
        <View style={styles.results}>
          <ScrollView
            keyboardShouldPersistTaps="handled"
            nestedScrollEnabled
            style={styles.resultsScroll}
          >
            {results.map((item) => (
              <Pressable
                key={item.videoId}
                style={({ pressed }) => [styles.item, pressed && styles.itemPressed]}
                onPress={() => selectVideo(item)}
              >
                {item.thumbnailUrl ? (
                  <Image source={{ uri: item.thumbnailUrl }} style={styles.thumb} />
                ) : (
                  <View style={[styles.thumb, styles.thumbPlaceholder]} />
                )}
                <View style={styles.itemBody}>
                  <Text style={styles.title} numberOfLines={2}>
                    {item.title}
                  </Text>
                  {item.channelTitle ? (
                    <Text style={styles.channel} numberOfLines={1}>
                      {item.channelTitle}
                    </Text>
                  ) : null}
                </View>
              </Pressable>
            ))}
          </ScrollView>
        </View>
      ) : null}
    </View>
  );
}

function createStyles(colors: ThemeColors) {
  return StyleSheet.create({
    root: {
      gap: 10,
    },
    field: {
      position: 'relative',
    },
    searchIcon: {
      position: 'absolute',
      left: 14,
      top: 0,
      bottom: 0,
      justifyContent: 'center',
      zIndex: 1,
    },
    input: {
      height: 40,
      paddingLeft: 40,
      backgroundColor: `${colors.background}99`,
      borderColor: `${colors.border}99`,
    },
    status: {
      fontSize: 12,
      color: colors.muted,
    },
    error: {
      fontSize: 12,
      color: colors.destructive,
    },
    results: {
      maxHeight: 220,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: `${colors.border}99`,
      backgroundColor: colors.background,
      overflow: 'hidden',
    },
    resultsScroll: {
      maxHeight: 220,
    },
    item: {
      flexDirection: 'row',
      gap: 12,
      paddingHorizontal: 10,
      paddingVertical: 10,
    },
    itemPressed: {
      backgroundColor: colors.mutedBg,
    },
    thumb: {
      width: 48,
      height: 36,
      borderRadius: 6,
      backgroundColor: colors.mutedBg,
    },
    thumbPlaceholder: {
      backgroundColor: colors.muted,
    },
    itemBody: {
      flex: 1,
      justifyContent: 'center',
      minWidth: 0,
    },
    title: {
      fontSize: 13,
      fontWeight: '500',
      color: colors.foreground,
    },
    channel: {
      fontSize: 11,
      color: colors.muted,
      marginTop: 2,
    },
  });
}
